[package]
name = "ponder-this"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
rand = "0.8.5"
rand_distr = "0.4.3"
